version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8820:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - weblab820

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8821:80"
    depends_on:
      - db
    networks:
      - weblab820

networks:
  weblab820:
    driver: bridge

volumes:
  mysql_data:
    driver: local